### ISSUE TITLE
Ter Avisa-me em variação

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-offers-notification#12]
Por enquanto, o avisa-me de estoque por exemplo, só aparece quando todas as variações estão sem estoque, por se tratar de um produto com variação, seria interessante ter para cada variação sem estoque.

**Comment by talissonf** [comment]
@matheusgnreis esse improve deve ser feito no storefront, é ele quem valida o estoque e libera o widget para exibição na página do produto.

**Comment by leomp12** [comment]
@talissonf na verdade tem que ser implementado aqui primeiro, ou já está?
Quer dizer, não adianta a gente deixar ele escolher a variação no Storefront mas em backend o app verificar apenas o estoque do produto, certo? Teria que salvar o ID ou SKU da variação e verificar se ele esquecificamente voltou a ter estoque...
