### ISSUE TITLE
Parou de funcionar avisa-me ou notificações

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-offers-notification#13]
![avisa-me](https://user-images.githubusercontent.com/35343551/101941708-24640f00-3bc7-11eb-9718-eeb19b2f471f.png)
Exemplo https://storefront-demo.e-com.plus/combo-teclado-e-mouse-thermaltake-kb-cmc-plblpb-01-preto

**Comment by leomp12** [comment]
@matheusgnreis nesse link aí está funcionando :thinking:

**Comment by matheusgnreis** [comment]
https://belabruna.com.br/vestido-argola-envelope-animal-print
Em alguns funcionam em guia anônima apenas. Esse aí não consegui, nem o lojista

**Comment by talissonf** [comment]
@matheusgnreis eu testei aqui e funcionou em guia normal e anônima.

**Comment by matheusgnreis** [comment]
@talissonf fato é que não está funcionando pra ninguem fora vc e leo, mais uma abertura de ticket na comunidade sobre isso.

**Comment by matheusgnreis** [comment]
Já testei em safari no macbook, no windows via chrome e nada. Só quando coloco guia anonima

**Comment by talissonf** [comment]
@matheusgnreis  quando ocorrer isso tenta ver o console do popup pra ver se tem alguma informação relevante porque o app não tem log de erros pra isso.

**Comment by matheusgnreis** [comment]
É o adblock, está indentificando como link de propaganda. No caso do iframe deve resolver, pelo teste q fiz

**Comment by talissonf** [comment]
@matheusgnreis @leomp12 removi o jquery como dependência e uns javascript do boostrap tmb. Ta tudo em vanila agora, acho q esse problema com adblock foi resolvido.

Tambem inclui um spiner no iframe pra indicar que está sendo carregado https://talisson.ngrok.io/

**Comment by leomp12** [comment]
@talissonf acho que spinner na verdade deveria ser na view do app, não no Storefront antes do iframe como está agora...
Até apareceu um spinner mas ele some bem antes de o formulário ficar visível...
Além disso o iframe ainda está muito pequeno eu acho:

![Screenshot_2020-12-17 Teclado Gamer Fortrek Mecânico K5 RGB Outemu Blue Preto](https://user-images.githubusercontent.com/10326572/102536634-a8673c80-4088-11eb-905f-92f98ccf28d1.png)

Acho que deveria ter um `min-height` e `max-width` (com `width: 100%`) maior também

**Comment by leomp12** [comment]
https://github.com/ecomplus/storefront/commit/9c088473898da9584b3348e322f2cce549f601a8
