### ISSUE TITLE
App: Offers notification

### ISSUE THREAD

**Issue by leomp12** [ecomplus/app-offers-notification#4]
- [x] Notificações via AWS SES, cadastros salvos em Firestore (pronto né @talissonf ?);
- [x] Admin settings (tá pronto também @talissonf ?);
- [ ] Ícones para o Market e descrição em md (@vitorrgg dá uma mão aqui por favor);

**Comment by leomp12** [comment]
O nome do app não é tão descritivo, mas resumidamente é o _avise-se quando chegar_ e/ou _avise-me quando o preço baixar_ :+1:

**Comment by talissonf** [comment]
Eu preciso fazer o admin_settings :$

**Comment by leomp12** [comment]
hahaha bora então, coragem

**Comment by talissonf** [comment]
vou fazer, esse é pequeno

**Comment by talissonf** [comment]
https://github.com/ecomplus/app-offers-notification/commit/b94820e35d873b0c2d2009a0d60d052ce04718e5

**Comment by talissonf** [comment]
https://github.com/ecomplus/app-offers-notification/commit/0720e7cb283f86f8fdd1c88aeefc5d09eec8e449

**Comment by leomp12** [comment]
@talissonf pode inserir o ícone lá, adicionar uma descriçãozinha e publicar pra nós por favor? Aí fechamos o issue...

**Comment by talissonf** [comment]
https://github.com/ecomplus/app-offers-notification/commit/10676657f3a1b0dce40e457ecaab59461d8ee1c1
